demolaravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::get('/', 'PagesController@index');
Route::get('/impressum', 'PagesController@imprint');
Route::get('/kontakt', 'PagesController@contact');

Route::get('/home', 'MemesController@getDailyLuck');

Route::resource('admin/product', 'ProductController');
Route::resource('books', 'BookController');

demolaravel/app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = ['book_name', 'isbn_no', 'book_price'];
}

demolaravel/app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::all();
        return view('book.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'book_name' => 'required|max:255',
            'isbn_no' => 'required|alpha_num',
            'book_price' => 'required|numeric',
        ]);

        $book = Book::create($validatedData);

        return redirect('/books')->with('success', 'Book is successfully saved');    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);

        return view('book.edit', compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'book_name' => 'required|max:255',
            'isbn_no' => 'required|alpha_num',
            'book_price' => 'required|numeric',
        ]);

        Book::whereId($id)->update($validatedData);

        return redirect('/books')->with('success', 'Book is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::findOrFail($id);
        $book->delete();

        return redirect('/books')->with('success', 'Book is successfully deleted');
    }
}

demolaravel/resources/views/book/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="card">
            <h5 class="card-header">Add Book</h5>
            <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger" role="alert">
                    <ul>
                        @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form action="{{ route('books.store') }}" method="post">
            <div class="form-group">
               @csrf
                <label for="name">Book Name:</label>
                <input id="book_name" class="form-control" name="book_name" type="text" placeholder="Book Name"/>
            </div>
            <div class="form-group">
                <label for="isbn_no">Book ISBN Number:</label> 
                <input type="text" id="isbn_no" class="form-control" name="isbn_no" placeholder="ISBN Number"/>
            </div>
            <div class="form-group">
                <label for="book_price">Book Price:</label> 
                <input id="book_price" class="form-control" name="book_price" type="number" placeholder="Price"/>
            </div>
            <button class="btn btn-primary" type="submit">Create Book</button>
            </form>
        </div>
    </div>
</div>
@endsection

demolaravel/resources/views/book/edit.blade.php
@extends('layouts.app')

@section('content')
<h2>Edit Book</h2>
<div class="card">
   <div class="card-body">
      @if ($errors->any())
         <div class="alert alert-danger m-2">
         <ul>
            @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
            @endforeach
         </ul>
         </div><br />
      @endif
      <form method="post" action="{{ route('books.update', $book->id) }}">
         <div class="form-group">
            @csrf
            @method('PATCH')
            <label for="name">Book Name:</label>
            <input type="text" class="form-control" name="book_name" value="{{$book->book_name}}"/>
         </div>
         <div class="form-group">
            <label for="price">Book ISBN Number :</label>
            <input type="text" class="form-control" name="isbn_no" value="{{$book->isbn_no}}"/>
         </div>
         <div class="form-group">
            <label for="quantity">Book Price :</label>
            <input type="number" class="form-control" name="book_price" value="{{$book->book_price}}"/>
         </div>
         <button type="submit" class="btn btn-primary">Update Book</button>
      </form>
   </div>
</div>
@endsection

demolaravel/resources/views/book/index.blade.php
@extends('layouts.app')

@section('content')
<h2>Books</h2>
<div class="card">
    <div class="card-body">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}  
            </div><br />
        @endif
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Book Name</td>
                    <td>ISBN Number</td>
                    <td>Book Price</td>
                    <td colspan="2">Action</td>
                </tr>
            </thead>
            <tbody>
                @foreach($books as $book)
                <tr>
                    <td>{{$book->id}}</td>
                    <td>{{$book->book_name}}</td>
                    <td>{{$book->isbn_no}}</td>
                    <td>$ {{ number_format(($book->book_price/100), 2)}}</td>
                    <td><a href="{{ route('books.edit',$book->id)}}" class="btn btn-primary btn-sm">Edit</a></td>
                    <td>
                        <form action="{{ route('books.destroy', $book->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection 