mysite/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::view('/demo', 'demo')->name('demo');
Route::view('/index','team');

Route::resource('members', 'MemberController');

mysite/app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'imgurl', 'jobfct','email','phone'
    ];
}

mysite/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

mysite/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

mysite/app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Member;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $members = Member::all();
        return view('index', compact('members'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'jobfct' => 'required|max:255',
            'email' => 'required|email',
            'phone' => 'required|max:255',
        ]);
        
        $member = Member::create($validatedData);
   
        return redirect('/members')->with('success', 'Member is successfully saved');
    }

 /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $member = Member::findOrFail($id);
        return view('show',compact('member'));
    }
/**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $member = Member::findOrFail($id);
        return view('edit', compact('member'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'jobfct' => 'required|max:255',
            'email' => 'required|email',
            'phone' => 'required|max:255',
        ]);

        Member::whereId($id)->update($validatedData);

        return redirect('/members')->with('success', 'Member is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $member = Member::findOrFail($id);
        $member->delete();

        return redirect('/members')->with('success', 'Member is successfully deleted');
    }}

mysite/resources/views/create.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-card">
  <h4 class="uk-card-title">
    Add Employee
  </h4>
  <div class="uk-card-body">
    @if ($errors->any())
      <div class="uk-alert-danger" uk-alert>
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif

      <form method="post" action="{{ route('members.store') }}">
          <div class="uk-margin">
              @csrf
              <label for="name">Member Name:</label>
              <input type="text" class="uk-input" name="name"/>
          </div>
          <div class="uk-margin">
              <label for="imgurl">Member Pict:</label>
              <input type="text" class="uk-input" name="imgurl"/>
          </div>
          <div class="uk-margin">
              <label for="jobfct">Member Job function:</label>
              <input type="text" class="uk-input" name="jobfct"/>
          </div>
          <div class="uk-margin">
              <label for="email">Member Email:</label>
              <input type="text" class="uk-input" name="email"/>
          </div>
          <div class="uk-margin">
              <label for="phone">Member Phone:</label>
              <input type="text" class="uk-input" name="phone"/>
          </div>
          <button type="submit" class="uk-button uk-button-primary">Create Member</button>
      </form>
  </div>
</div>
@endsection

mysite/resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-card">
  <h5 class="uk-card-title">
    Update Members
</h5>
  <div class="uk-card-body">
    @if ($errors->any())
      <div class="uk-alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    <form method="post" action="{{ route('members.update', $member->id) }}">
          <div class="uk-margin">
              @csrf
              @method('PATCH')
              <label for="name">Name:</label>
              <input type="text" class="uk-input" name="name" value="{{ $member->name }}"/>
          </div>
          <div class="uk-margin">
              <label for="imgurl">Bild:</label>
              <input type="text" class="uk-input" name="imgurl" value="{{ $member->imgurl}}"/>
          </div>
          <div class="uk-margin">
              <label for="jobfct">Job function:</label>
              <input type="text" class="uk-input" name="jobfct" value="{{ $member->jobfct }}"/>
          </div>
          <div class="uk-margin">
              <label for="email">Email:</label>
              <input type="text" class="uk-input" name="email" value="{{ $member->email }}"/>
          </div>

          <div class="uk-margin">
              <label for="phone">Phone:</label>
              <input type="text" class="uk-input" name="phone" value="{{ $member->phone }}"/>
          </div>
          <button type="submit" class="uk-button uk-button-primary">Update Member</button>
      </form>
  </div>
</div>
@endsection

mysite/resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<div>
  @if(session()->get('success'))
    <div uk-alert>
      <a class="uk-alert-close" uk-close></a>
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <p class="uk-margin-top">
    <a class="uk-button uk-button-primary" href="{{ route('members.create')}}">Create member</a>
  </p>

  <table class="uk-table uk-table-striped">
    <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Image</th>
          <th>Function</th>
          <th>Email</th>
          <th>Phone</th>
          <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($members as $member)
        <tr>
            <td><a href="{{ route('members.show', $member->id)}}">{{$member->id}}</a></td>
            <td>{{$member->name}}</td>
            <td>{{$member->imgurl}}</td>
            <td>{{$member->jobfct}}</td>
            <td>{{$member->email}}</td>
            <td>{{$member->phone}}</td>
            <td><a href="{{ route('members.edit', $member->id)}}" class="uk-button uk-button-primary uk-button-small">Edit</a></td>
            <td>
                <form action="{{ route('members.destroy', $member->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="uk-button uk-button-danger uk-button-small" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection

mysite/resources/views/laravel.blade.php
<li><a target="_blank" href="https://laravel.com/">Laravel Website</a></li>
<li><a target="_blank" href="https://laravel.com/docs">Laravel Docs</a></li>
<li><a target="_blank" href="https://laracasts.com">Laracasts</a></li>
<li><a target="_blank" href="https://laravel-news.com">Laravel News</a></li>
<li><a target="_blank" href="https://blog.laravel.com">Laravel Blog</a></li>
<li><a target="_blank" href="https://github.com/laravel/laravel">Laravel on GitHub</a></li>
<li><a target="_blank" href="https://github.com/chiraggude/awesome-laravel">Awesome Laravel</a></li>

mysite/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <div class="uk-background-primary uk-light">
        <nav class="uk-navbar-container uk-navbar-transparent">
            <div class="uk-container">
                <div class="uk-navbar" data-uk-navbar>
                    <div class="uk-navbar-left">
                        <a class="uk-navbar-item uk-logo" href="/">{{ config('app.name', 'Laravel') }}</a>

                        <ul class="uk-navbar-nav">
                            <li><a href="{{ route('demo') }}">Theme Demo</a></li>
                            <li>
                                <a href="#">Useful Links</a>
                                <div class="uk-navbar-dropdown uk-navbar-dropdown-width-3">
                                    <div class="uk-navbar-dropdown-grid uk-child-width-1-3" data-uk-grid>
                                        <div>
                                            <ul class="uk-nav uk-navbar-dropdown-nav">
                                                <li class="uk-nav-header">Laravel</li>
                                                @include('laravel')
                                            </ul>
                                        </div>
                                        <div>
                                            <ul class="uk-nav uk-navbar-dropdown-nav">
                                                <li class="uk-nav-header">UIkit</li>
                                                @include('uikit')
                                            </ul>
                                        </div>
                                        <div>
                                            <ul class="uk-nav uk-navbar-dropdown-nav">
                                                <li class="uk-nav-header">Vue.js</li>
                                                @include('vuejs')
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li><a href="/members">Team</a></li>
                        </ul>
                    </div>
                    <div class="uk-navbar-right">
                        <ul class="uk-navbar-nav">
                            <!-- Authentication Links -->
                            @guest
                                @if (Route::has('login'))
                                    <li>
                                        <a href="{{ route('login') }}">{{ __('Log In') }}</a>
                                    </li>
                                @endif
                                @if (Route::has('register'))
                                    <li>
                                        <a href="{{ route('register') }}">{{ __('Register') }}</a>
                                    </li>
                                @endif
                            @else
                                <li>
                                    <a href="#">
                                        {{ Auth::user()->name }}
                                    </a>
                                    <div class="uk-navbar-dropdown">
                                        <ul class="uk-nav uk-navbar-dropdown-nav">
                                            <li>
                                                <a href="{{ route('logout') }}"
                                                onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                                    {{ __('Log Out') }}
                                                </a>

                                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                                    style="display: none;">
                                                    @csrf
                                                </form>
                                            </li>
                                        </ul>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <main class="uk-container">
        @yield('content')
    </main>

    <footer class="uk-section uk-section-xsmall uk-section-secondary">
        <div class="uk-container">
            <div class="uk-grid uk-text-center uk-text-left@s uk-flex-middle" data-uk-grid>
                <div class="uk-text-small uk-text-muted uk-width-1-3@s">
                    &copy;2019, J. Polzin
                </div>
                <div class="uk-text-small uk-text-muted uk-text-center uk-text-right@s uk-width-1-2@s">
                    Built with <a target="_blank" href="http://getuikit.com"><span data-uk-icon="uikit"></span></a>
                </div>
            </div>
        </div>
    </footer>
</div>
<script src="{{ asset('js/app.js') }}" defer></script>
</body>
</html>

mysite/resources/views/show.blade.php
@extends('layouts.app')

@section('content')
<h3>Show member</h3>
<div class="uk-child-width-1-2 uk-grid-small" uk-grid>
   <div class="uk-card uk-card-default uk-width-1-3@m uk-margin-bottom">
      <div class="uk-card-header">
         <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-auto">
               <img class="uk-border-rounded" width="80" data-src="{{ asset('img') }}/{{$member->imgurl}}" uk-img>
            </div>
            <div class="uk-width-expand">
               <h3 class="uk-card-title uk-margin-remove-bottom">{{ $member->name}}</h3>
            </div>
         </div>
      </div>
      <div class="uk-card-body">
         <p class="uk-text-small">
            Function:&nbsp;{{ $member->jobfct}}<br/>
            Email:&nbsp;{{ $member->email}}<br/>
            Mobile:&nbsp;{{ $member->phone}}
         </p>
      </div>
      <p class="uk-margin-small-bottom">
         <a class="uk-button uk-button-primary uk-button-small" href="/members">Back</a>
      </p>
   </div>
</div>
@endsection

mysite/resources/views/uikit.blade.php
<li><a target="_blank" href="https://getuikit.com/">UIkit Website</a></li>
<li><a target="_blank" href="https://getuikit.com/docs">UIkit Docs</a></li>
<li><a target="_blank" href="https://getuikit.com/changelog">UIkit Changelog</a></li>
<li><a target="_blank" href="https://twitter.com/getuikit">UIkit on Twitter</a></li>
<li><a target="_blank" href="https://github.com/uikit/uikit">UIkit on GitHub</a></li>
<li><a target="_blank" href="https://github.com/uikit/awesome-uikit">Awesome UIkit</a></li>
<li><a target="_blank" href="https://zzseba78.github.io/Kick-Off/">KickOff - Starter Templates</a></li>

mysite/resources/views/vuejs.blade.php
<li><a target="_blank" href="https://vuejs.org/">Vue.js Website</a></li>
<li><a target="_blank" href="https://vuejs.org/v2/guide/">Vue.js Guide</a></li>
<li><a target="_blank" href="https://news.vuejs.org/">Vue.js News</a></li>
<li><a target="_blank" href="https://medium.com/the-vue-point">Vue.js Blog</a></li>
<li><a target="_blank" href="https://github.com/vuejs/vue">Vue.js on GitHub</a></li>
<li><a target="_blank" href="https://github.com/vuejs/awesome-vue">Awesome Vue</a></li>